-- ============================================================
--  VibeCraft — self-registered teams + Ender Dragon (Round 2, Phase 2)
--  Run in the Supabase SQL editor AFTER schema.sql. Safe to re-run.
--
--  Nothing secret lives in this file (the repo is public):
--    • the server secret's HASH and the level prompts are inserted separately
--      from supabase/private/ (git-ignored) — see DRAGON_RUNBOOK.md.
--
--  Access model:
--    • Participants never touch these tables. The Vercel function /api/dragon calls the
--      dragon_* functions below with a server secret; each one checks that secret first.
--    • The organiser (same email as the timer policy) uses the admin_* functions and may
--      read/update dragon_config from /admin.
-- ============================================================

create extension if not exists pgcrypto with schema extensions;

-- ---------- helpers ------------------------------------------------------------
create or replace function public.is_admin()
returns boolean language sql stable as $$
  select lower(coalesce(auth.jwt() ->> 'email', '')) = lower('Supabasentt@gmail.com');
$$;

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

-- ---------- tables -------------------------------------------------------------
-- Teams register themselves (no pre-loaded list). The team key is only ever stored hashed.
create table if not exists public.teams (
  id                 bigint generated by default as identity primary key,
  name               text not null,
  name_key           text not null unique,        -- lowercase letters+digits, for duplicate checks
  key_hash           text not null unique,        -- sha256 of the upper-cased team key
  created_at         timestamptz not null default now(),
  last_msg_at        timestamptz,                 -- Dragon cooldown
  guess_window_start timestamptz,                 -- Dragon guess rate limit
  guess_count        int not null default 0
);
alter table public.teams enable row level security;

-- sha256 of server secrets (the raw secret only exists in Vercel / .env.local).
create table if not exists public.server_secrets (
  name        text primary key,
  secret_hash text not null
);
alter table public.server_secrets enable row level security;

create table if not exists public.dragon_config (
  id              int primary key default 1 check (id = 1),
  status          text not null default 'closed' check (status in ('closed', 'open', 'paused')),
  llm_url         text not null default 'http://localhost:1234',
  llm_model       text not null default 'dragon',
  cooldown_s      int  not null default 30  check (cooldown_s between 0 and 600),
  global_per_min  int  not null default 300 check (global_per_min between 1 and 5000),
  guesses_per_min int  not null default 6   check (guesses_per_min between 1 and 60),
  updated_at      timestamptz not null default now()
);
insert into public.dragon_config (id) values (1) on conflict (id) do nothing;
alter table public.dragon_config enable row level security;

drop policy if exists "dragon config admin read" on public.dragon_config;
create policy "dragon config admin read" on public.dragon_config
  for select using (public.is_admin());
drop policy if exists "dragon config admin update" on public.dragon_config;
create policy "dragon config admin update" on public.dragon_config
  for update using (public.is_admin()) with check (public.is_admin());

drop trigger if exists dragon_config_touch on public.dragon_config;
create trigger dragon_config_touch before update on public.dragon_config
  for each row execute function public.touch_updated_at();

-- Levels: prompts are secret ({{PASSWORD}} is replaced per team). Edit them live in the
-- Table Editor — the server re-reads them every ~15 s.
create table if not exists public.dragon_levels (
  level         int primary key check (level between 1 and 5),
  title         text not null,
  intro         text not null,                    -- shown to players
  system_prompt text not null,                    -- secret
  blocked_words text[] not null default '{}',     -- whole-word, case-insensitive input filter
  output_filter text not null default 'none' check (output_filter in ('none', 'exact', 'strict')),
  points        int  not null default 1
);
alter table public.dragon_levels enable row level security;

create table if not exists public.dragon_clears (
  team_id    bigint not null references public.teams (id) on delete cascade,
  level      int not null,
  cleared_at timestamptz not null default now(),
  primary key (team_id, level)
);
alter table public.dragon_clears enable row level security;

create table if not exists public.dragon_msgs (
  id         bigint generated by default as identity primary key,
  team_id    bigint not null references public.teams (id) on delete cascade,
  level      int not null,
  message    text not null,
  created_at timestamptz not null default now()
);
create index if not exists dragon_msgs_created_at on public.dragon_msgs (created_at);
create index if not exists dragon_msgs_team on public.dragon_msgs (team_id);
alter table public.dragon_msgs enable row level security;

-- ---------- internal helpers (not callable by participants) -------------------
create or replace function public.dragon_check_server(p_secret text)
returns void language plpgsql security definer set search_path = public, extensions as $$
begin
  if p_secret is null or not exists (
    select 1 from public.server_secrets
    where name = 'dragon' and secret_hash = encode(extensions.digest(p_secret, 'sha256'), 'hex')
  ) then
    raise exception 'forbidden' using errcode = '42501';
  end if;
end $$;

create or replace function public.team_key_hash(p_key text)
returns text language sql immutable set search_path = public, extensions as $$
  select encode(extensions.digest(upper(btrim(coalesce(p_key, ''))), 'sha256'), 'hex');
$$;

revoke all on function public.dragon_check_server(text) from public, anon, authenticated;
revoke all on function public.team_key_hash(text) from public, anon, authenticated;

-- ---------- server functions (called by /api/dragon with the server secret) ---
-- Everything the server caches: config + all levels (incl. secret prompts).
create or replace function public.dragon_server_config(p_secret text)
returns jsonb language plpgsql security definer set search_path = public, extensions as $$
begin
  perform public.dragon_check_server(p_secret);
  return jsonb_build_object(
    'config', (select to_jsonb(c) from public.dragon_config c where c.id = 1),
    'levels', coalesce((select jsonb_agg(to_jsonb(l) order by l.level) from public.dragon_levels l), '[]'::jsonb)
  );
end $$;

-- Register a team. Raises 'bad_name' | 'name_taken' | 'team_limit'.
create or replace function public.dragon_team_setup(p_secret text, p_name text, p_key text)
returns jsonb language plpgsql security definer set search_path = public, extensions as $$
declare
  v_name     text := regexp_replace(btrim(coalesce(p_name, '')), '\s+', ' ', 'g');
  v_name_key text;
  v_id       bigint;
begin
  perform public.dragon_check_server(p_secret);
  v_name_key := regexp_replace(lower(v_name), '[^a-z0-9]', '', 'g');
  if char_length(v_name) not between 2 and 40 or char_length(v_name_key) < 2 then
    raise exception 'bad_name';
  end if;
  if exists (select 1 from public.teams where name_key = v_name_key) then
    raise exception 'name_taken';
  end if;
  if (select count(*) from public.teams) >= 400 then
    raise exception 'team_limit';
  end if;
  insert into public.teams (name, name_key, key_hash)
  values (v_name, v_name_key, public.team_key_hash(p_key))
  returning id into v_id;
  return jsonb_build_object('id', v_id, 'name', v_name);
exception
  when unique_violation then raise exception 'name_taken';
end $$;

-- Page state for a team key (team is null when the key is unknown).
create or replace function public.dragon_status(p_secret text, p_key text)
returns jsonb language plpgsql security definer set search_path = public, extensions as $$
declare
  c public.dragon_config;
  t public.teams;
begin
  perform public.dragon_check_server(p_secret);
  select * into c from public.dragon_config where id = 1;
  select * into t from public.teams where key_hash = public.team_key_hash(p_key);
  if t.id is null then
    return jsonb_build_object('status', c.status, 'team', null);
  end if;
  return jsonb_build_object(
    'status', c.status,
    'team', jsonb_build_object('id', t.id, 'name', t.name),
    'cleared', coalesce((select jsonb_agg(d.level order by d.level) from public.dragon_clears d where d.team_id = t.id), '[]'::jsonb),
    'cooldown_s', c.cooldown_s,
    'cooldown_left', greatest(0, ceil(extract(epoch from (t.last_msg_at + make_interval(secs => c.cooldown_s) - now()))))::int,
    'levels', coalesce((
      select jsonb_agg(jsonb_build_object('level', l.level, 'title', l.title, 'intro', l.intro, 'points', l.points) order by l.level)
      from public.dragon_levels l), '[]'::jsonb)
  );
end $$;

-- Gate + log one chat message. Returns {ok:false, reason, retry_after?} or {ok:true, ...}.
create or replace function public.dragon_chat_begin(p_secret text, p_key text, p_level int, p_message text)
returns jsonb language plpgsql security definer set search_path = public, extensions as $$
declare
  c        public.dragon_config;
  t        public.teams;
  v_recent int;
  v_msg_id bigint;
begin
  perform public.dragon_check_server(p_secret);
  select * into c from public.dragon_config where id = 1;
  if c.status <> 'open' then
    return jsonb_build_object('ok', false, 'reason', c.status);
  end if;

  -- lock the team row so two teammates' laptops can't both skip the cooldown
  select * into t from public.teams where key_hash = public.team_key_hash(p_key) for update;
  if t.id is null then
    return jsonb_build_object('ok', false, 'reason', 'no_team');
  end if;
  if not exists (select 1 from public.dragon_levels where level = p_level) then
    return jsonb_build_object('ok', false, 'reason', 'bad_level');
  end if;
  if p_level > 1 and not exists (select 1 from public.dragon_clears where team_id = t.id and level = p_level - 1) then
    return jsonb_build_object('ok', false, 'reason', 'locked');
  end if;
  if exists (select 1 from public.dragon_clears where team_id = t.id and level = p_level) then
    return jsonb_build_object('ok', false, 'reason', 'already_cleared');
  end if;
  if t.last_msg_at is not null and t.last_msg_at > now() - make_interval(secs => c.cooldown_s) then
    return jsonb_build_object('ok', false, 'reason', 'cooldown', 'retry_after',
      greatest(1, ceil(extract(epoch from (t.last_msg_at + make_interval(secs => c.cooldown_s) - now())))::int));
  end if;

  select count(*) into v_recent from public.dragon_msgs where created_at > now() - interval '60 seconds';
  if v_recent >= c.global_per_min then
    return jsonb_build_object('ok', false, 'reason', 'busy', 'retry_after', 8);
  end if;

  insert into public.dragon_msgs (team_id, level, message)
  values (t.id, p_level, left(coalesce(p_message, ''), 1000))
  returning id into v_msg_id;
  update public.teams set last_msg_at = now() where id = t.id;

  return jsonb_build_object('ok', true, 'team_id', t.id, 'msg_id', v_msg_id,
                            'prev_last', t.last_msg_at, 'cooldown_s', c.cooldown_s);
end $$;

-- Undo a message whose AI reply failed, so it doesn't cost the team its turn.
create or replace function public.dragon_chat_refund(p_secret text, p_msg_id bigint, p_prev_last timestamptz)
returns void language plpgsql security definer set search_path = public, extensions as $$
begin
  perform public.dragon_check_server(p_secret);
  update public.teams t set last_msg_at = p_prev_last
    from public.dragon_msgs m
   where m.id = p_msg_id and t.id = m.team_id;
  delete from public.dragon_msgs where id = p_msg_id;
end $$;

-- Gate a password guess (rate-limited per team). The server compares the password itself.
create or replace function public.dragon_guess_begin(p_secret text, p_key text, p_level int)
returns jsonb language plpgsql security definer set search_path = public, extensions as $$
declare
  c public.dragon_config;
  t public.teams;
begin
  perform public.dragon_check_server(p_secret);
  select * into c from public.dragon_config where id = 1;
  if c.status <> 'open' then
    return jsonb_build_object('ok', false, 'reason', c.status);
  end if;
  select * into t from public.teams where key_hash = public.team_key_hash(p_key) for update;
  if t.id is null then
    return jsonb_build_object('ok', false, 'reason', 'no_team');
  end if;
  if p_level > 1 and not exists (select 1 from public.dragon_clears where team_id = t.id and level = p_level - 1) then
    return jsonb_build_object('ok', false, 'reason', 'locked');
  end if;
  if exists (select 1 from public.dragon_clears where team_id = t.id and level = p_level) then
    return jsonb_build_object('ok', false, 'reason', 'already_cleared');
  end if;

  if t.guess_window_start is null or t.guess_window_start < now() - interval '60 seconds' then
    update public.teams set guess_window_start = now(), guess_count = 1 where id = t.id;
  elsif t.guess_count >= c.guesses_per_min then
    return jsonb_build_object('ok', false, 'reason', 'guess_limit', 'retry_after',
      greatest(1, ceil(extract(epoch from (t.guess_window_start + interval '60 seconds' - now())))::int));
  else
    update public.teams set guess_count = guess_count + 1 where id = t.id;
  end if;

  return jsonb_build_object('ok', true, 'team_id', t.id);
end $$;

create or replace function public.dragon_clear(p_secret text, p_team_id bigint, p_level int)
returns jsonb language plpgsql security definer set search_path = public, extensions as $$
begin
  perform public.dragon_check_server(p_secret);
  insert into public.dragon_clears (team_id, level) values (p_team_id, p_level)
  on conflict (team_id, level) do nothing;
  return jsonb_build_object('points', (select points from public.dragon_levels where level = p_level));
end $$;

-- ---------- organiser functions (/admin, signed in as the organiser) ----------
create or replace function public.admin_dragon_overview()
returns jsonb language plpgsql security definer set search_path = public, extensions as $$
begin
  if not public.is_admin() then
    raise exception 'forbidden' using errcode = '42501';
  end if;
  return jsonb_build_object(
    'config', (select to_jsonb(c) from public.dragon_config c where c.id = 1),
    'msgs_last_min', (select count(*) from public.dragon_msgs where created_at > now() - interval '60 seconds'),
    'msgs_total', (select count(*) from public.dragon_msgs),
    'levels', coalesce((
      select jsonb_agg(jsonb_build_object(
        'level', l.level, 'title', l.title,
        'cleared_by', (select count(*) from public.dragon_clears d where d.level = l.level)) order by l.level)
      from public.dragon_levels l), '[]'::jsonb),
    'teams', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', t.id, 'name', t.name, 'created_at', t.created_at,
        'cleared', coalesce((select jsonb_agg(d.level order by d.level) from public.dragon_clears d where d.team_id = t.id), '[]'::jsonb),
        'msgs', (select count(*) from public.dragon_msgs m where m.team_id = t.id)) order by t.name_key)
      from public.teams t), '[]'::jsonb)
  );
end $$;

-- Give a team a new key (e.g. someone else registered their name, or they lost it).
create or replace function public.admin_team_reset_key(p_team_id bigint, p_key text)
returns void language plpgsql security definer set search_path = public, extensions as $$
begin
  if not public.is_admin() then
    raise exception 'forbidden' using errcode = '42501';
  end if;
  update public.teams set key_hash = public.team_key_hash(p_key) where id = p_team_id;
end $$;

create or replace function public.admin_team_delete(p_team_id bigint)
returns void language plpgsql security definer set search_path = public, extensions as $$
begin
  if not public.is_admin() then
    raise exception 'forbidden' using errcode = '42501';
  end if;
  delete from public.teams where id = p_team_id;
end $$;
