-- ============================================================
--  VibeCraft — Supabase schema
--  Run this in the Supabase SQL editor (Dashboard → SQL → New query).
--  The organiser admin email is set in the timer policy below.
--  Safe to re-run: it upgrades existing objects in place.
-- ============================================================

-- ---------- 1) TIMER ----------------------------------------
create table if not exists public.timer_state (
  id           integer primary key default 1,
  status       text not null default 'idle'
                 check (status in ('idle','running','paused','ended')),
  ends_at      timestamptz,
  remaining_ms bigint,
  duration_ms  bigint not null default 32400000,  -- 9h default (editable live)
  updated_at   timestamptz not null default now(),
  constraint timer_single_row check (id = 1)
);

insert into public.timer_state (id) values (1)
  on conflict (id) do nothing;

alter table public.timer_state enable row level security;

-- everyone can READ the timer
drop policy if exists "timer read" on public.timer_state;
create policy "timer read" on public.timer_state
  for select using (true);

-- only the admin (matched by email in their JWT) can WRITE it
drop policy if exists "timer admin update" on public.timer_state;
create policy "timer admin update" on public.timer_state
  for update
  using      ( (auth.jwt() ->> 'email') = 'Supabasentt@gmail.com' )
  with check ( (auth.jwt() ->> 'email') = 'Supabasentt@gmail.com' );

-- keep updated_at fresh on every write
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

drop trigger if exists timer_touch on public.timer_state;
create trigger timer_touch before update on public.timer_state
  for each row execute function public.touch_updated_at();

-- broadcast row changes over Realtime (guarded so re-running the schema is safe)
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'timer_state'
  ) then
    alter publication supabase_realtime add table public.timer_state;
  end if;
end $$;

-- ---------- 2) ROUND 2 PROBLEM STATEMENTS (server-gated, a LIST) -----
-- Gate config: one row holding the access code.
create table if not exists public.round2 (
  id          integer primary key default 1,
  access_code text not null,
  constraint round2_single_row check (id = 1)
);
alter table public.round2 enable row level security;
-- No SELECT policy → the anon/public key can NEVER read the code.

-- The list of Round 2 problem statements (all secret). Add as many rows as you like.
create table if not exists public.round2_problems (
  id       bigint generated by default as identity primary key,
  sort_order int  not null default 0,   -- controls display order
  title    text not null,
  body     text not null
);
alter table public.round2_problems enable row level security;
-- No SELECT policy → anon can't read these directly.

-- The only way in: checks the code server-side and returns the WHOLE ordered list of
-- problems ONLY on a match. SECURITY DEFINER lets it read the tables while callers
-- still cannot. (Return type changed from earlier versions → drop first.)
drop function if exists public.verify_round2(text);
create function public.verify_round2(code text)
returns table(sort_order int, title text, body text)
language sql
security definer
set search_path = public
as $$
  select p.sort_order, p.title, p.body
  from public.round2_problems p
  where exists (
    select 1 from public.round2 r
    where r.id = 1 and upper(trim(code)) = upper(trim(r.access_code))
  )
  order by p.sort_order, p.id;
$$;

revoke all on function public.verify_round2(text) from public;
grant execute on function public.verify_round2(text) to anon, authenticated;

-- seed: a placeholder code + one placeholder problem (EDIT before the event)
insert into public.round2 (id, access_code) values (1, 'CHANGE-ME-BEFORE-EVENT')
  on conflict (id) do nothing;
insert into public.round2_problems (sort_order, title, body)
  select 1, 'Sample Problem 1', 'Replace this with a real Round 2 problem statement.'
  where not exists (select 1 from public.round2_problems);

-- Manage later (see ROUND2_PS_INSTRUCTIONS.md):
--   update public.round2 set access_code = 'REAL-CODE' where id = 1;
--   insert into public.round2_problems (sort_order, title, body) values (2, '…', $$…$$);
--   update public.round2_problems set title='…', body=$$…$$ where id = 1;
